# This is a basic workflow to help you get started with Actions

name: sos

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sos-lite:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: masterpi2124
          password: MasterPi_(2124)
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd rpi/lite
          sudo bash build.sh
      - name: Compress
        run: |
          sudo xz -T $(nproc) rpi/lite/images/sos-lite.img
          
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: sos
          path: rpi/lite/images/sos-lite.img.xz
